version: '3.8'

services:
  mailService:
    build:
      context: ./mailService
    image: raulmoya/mailservice:1.0.0
    ports:
      - '3002:3001'
    depends_on:
      - database

  userService:
    build:
      context: ./userService
    image: raulmoya/userservice:1.0.0
    ports:
      - '3003:3001'
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
